Repository openstack-k8s-operators/test-operator, pull requests merged in 2024-08, with the labels that each got.

#154 Protect lock from deletion by different reconcile loop
  controllers/ansibletest_controller.go
  controllers/common.go
  controllers/horizontest_controller.go
  controllers/tempest_controller.go
  controllers/tobiko_controller.go
Labels: approved, lgtm

#170 Fix test-operator being stuck on NetworkAttachments error
  controllers/common.go
  controllers/tempest_controller.go
  controllers/tobiko_controller.go
Labels: approved, lgtm

#174 Enable networkAttachments testing in the check job
  .zuul.yaml
Labels: Ready For Review, approved, lgtm

#176 [Horizontest] Add workflowStep label
  controllers/horizontest_controller.go
Labels: approved, lgtm

#166 Add imageCreationTimeout parameter to Tempest CRD
  .zuul.yaml
  api/bases/test.openstack.org_tempests.yaml
  api/v1beta1/tempest_types.go
  config/crd/bases/test.openstack.org_tempests.yaml
  config/manifests/bases/test-operator.clusterserviceversion.yaml
  controllers/tempest_controller.go
Labels: Ready For Review, approved, lgtm, ok-to-test

#175 [docs] Update the documentation
  CONTRIBUTING.md
  README.md
  config/samples/test_v1beta1_horizontest.yaml
  docs/source/FAQ.rst
  docs/source/contributing.md
  docs/source/guide.rst
  docs/source/index.rst
Labels: approved, lgtm

#160 Add webhook for all CRs
  PROJECT
  api/bases/test.openstack.org_ansibletests.yaml
  api/v1beta1/ansibletest_types.go
  api/v1beta1/ansibletest_webhook.go
  api/v1beta1/horizontest_webhook.go
  api/v1beta1/tobiko_webhook.go
  config/crd/bases/test.openstack.org_ansibletests.yaml
  config/manifests/bases/test-operator.clusterserviceversion.yaml
  config/samples/test_v1beta1_ansibletest.yaml
  config/webhook/manifests.yaml
  docs/source/FAQ.rst
  docs/source/crds.rst
  hack/clean_local_webhook.sh
  hack/configure_local_webhook.sh
  main.go
Labels: Ready For Review, approved, lgtm

#173 Enable RuntimeDefault SeccompProfile
  config/manager/manager.yaml
  pkg/ansibletest/job.go
  pkg/horizontest/job.go
  pkg/tempest/job.go
  pkg/tobiko/job.go
Labels: Ready For Review, approved, lgtm

#186 [18.0.0-proposed] Protect lock from deletion by different reconcile loop
  controllers/ansibletest_controller.go
  controllers/common.go
  controllers/horizontest_controller.go
  controllers/tempest_controller.go
  controllers/tobiko_controller.go
Labels: approved, lgtm

#187 [18.0.0-proposed] Fix test-operator being stuck on NetworkAttachments error
  controllers/common.go
  controllers/tempest_controller.go
  controllers/tobiko_controller.go
Labels: approved, lgtm
